# yaml-language-server: $schema=../../schemas/yaml/services_schema.yaml
# Describes the format for available services for metiundo

reload_data:
  name: Reload Data
  description: Force a refresh of the integration data from the API
